data:
  path_patients: 'C:/Users/Ernesto/OneDrive - ETH Zurich/Desktop/MT/COMET/synthetic_data_generation/patients.csv'
  path_organs: 'C:/Users/Ernesto/OneDrive - ETH Zurich/Desktop/MT/COMET/synthetic_data_generation/organs.csv'
  path_outcomes: 'C:/Users/Ernesto/OneDrive - ETH Zurich/Desktop/MT/COMET/synthetic_data_generation/outcomes.csv'
  path_outcomes_noiseless: 'C:/Users/Ernesto/OneDrive - ETH Zurich/Desktop/MT/COMET/synthetic_data_generation/outcomes_noiseless.csv'
  path_effects: 'C:/Users/Ernesto/OneDrive - ETH Zurich/Desktop/MT/COMET/synthetic_data_generation/effects.csv'
  
synthetic_data:
  n : 500  # number of patients
  m :  500 # number of organs
  noise: 0
  complexity : 1
  only_factual : False
  TAB : 0 #Treatment assignment bias


evaluation:
  split : true
  scale : false
  trainfac : true
  evalfac : false
  learner : 'S_Learner()'
  outcome : 'survival'
  outcome_type : 'binary' #options: 'binary', 'continuous', ´categorical
  model : 'RandomForestClassifier()' #GradientBoostingRegressor(n_estimators=100, max_depth=6, min_samples_leaf=1)
  clustering_type : 'kmeans' #options: 'kmeans', 'expert', 'None'
  clustering_n_clusters : 5
  metric : 'AUPRC' #options: RMSE, AUROC, AUPRC, CATE 


 